{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "JarJarMetadata",
    "version": "0.3.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.machinezoo.noexception",
          "module": "noexception",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "JarJarMetadata-0.3.17.jar",
          "url": "JarJarMetadata-0.3.17.jar",
          "size": 15894,
          "sha512": "88d356bacd296ad6136c42f3e4b48bfc6053f69ff2fab359f781eb63accd9c35a5e135e80bc93158091b4e4616da36939708f21a35b12f99e5ed7e6e8808b699",
          "sha256": "62cf7a5fe9a6c141ef5dba667dc6102384d1e6b75a54ed5f4dc7b99c610985c5",
          "sha1": "113ea2c7abdd63c0c0ab72d3cd3e5eed1e5371a4",
          "md5": "f735bab2a463f35fb30d26f6314e646f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.machinezoo.noexception",
          "module": "noexception",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "JarJarMetadata-0.3.17.jar",
          "url": "JarJarMetadata-0.3.17.jar",
          "size": 15894,
          "sha512": "88d356bacd296ad6136c42f3e4b48bfc6053f69ff2fab359f781eb63accd9c35a5e135e80bc93158091b4e4616da36939708f21a35b12f99e5ed7e6e8808b699",
          "sha256": "62cf7a5fe9a6c141ef5dba667dc6102384d1e6b75a54ed5f4dc7b99c610985c5",
          "sha1": "113ea2c7abdd63c0c0ab72d3cd3e5eed1e5371a4",
          "md5": "f735bab2a463f35fb30d26f6314e646f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "JarJarMetadata-0.3.17-sources.jar",
          "url": "JarJarMetadata-0.3.17-sources.jar",
          "size": 8599,
          "sha512": "fe39d3b5b97d249444ab2f816223ad47e1feb20fcbd08e053a63e6c487d861259c3669891aa61601f10f0b929c2f4cdbedbd1ee16e1dcabe397be249531baef4",
          "sha256": "8d9722edf838ee4ae90114e2c7ce14c959273e35e8d0526b7efab9edc77069ba",
          "sha1": "c8ccb0ff535a487281ddbc52182a74a87a918bba",
          "md5": "db95c3cffae91312b06437ffcf903ae4"
        }
      ]
    }
  ]
}
